name: Publish to Nuget.org

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_solution:
    name: Build .NET Solution
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGETAUTHTOKEN }}
        with:
          source-url: https://api.nuget.org/v3/index.json
