name: Publish to Nuget.org

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x', '7.0.x' ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGETAUTHTOKEN }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build solution
        run: dotnet build -c Release
      - name: Run tests
        run: dotnet test
      - name: Build packages
        run: dotnet pack -c Release
  publish:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          source-url: https://api.nuget.org/v3/index.json
      - name: Publish Nuget packages
        run: dotnet nuget push SimpleMessageBus/bin/Release/SimpleMessageBus.*.nupkg --api-key ${{ secrets.NUGETAUTHTOKEN }}
